[server]
maxUploadSize = 500

[theme]
primaryColor="#005CA9"             # Azul CAIXA
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F5F7FB" # Fundo cartões
textColor="#1E1E1E"
font="sans serif"